/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Zen's Atelier",
  "tagline": "동기화를 중요하게 생각하는 프론트앤드 개발자",
  "favicon": "img/favicon.ico",
  "url": "https://fantasmith.com",
  "baseUrl": "/",
  "organizationName": "effozen",
  "projectName": "FantaSmith",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "ko",
    "locales": [
      "ko",
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "docs",
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/effozen/fantasmith/tree/main/",
          "showLastUpdateTime": true
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/effozen/fantasmith/tree/main/",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn",
          "blogSidebarTitle": "📝 목차",
          "routeBasePath": "blog"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "gtag": {
          "trackingID": "G-TNMDGQWQYM",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "Zen's Atelier",
      "logo": {
        "alt": "사이트 로고",
        "src": "img/logo.webp"
      },
      "items": [
        {
          "to": "/blog",
          "label": "🚀 성장 이야기",
          "position": "left"
        },
        {
          "href": "https://github.com/effozen",
          "label": "GitHub",
          "position": "right"
        },
        {
          "type": "docSidebar",
          "sidebarId": "boostcampSidebar",
          "position": "left",
          "label": "🧑‍💻 네부캠 프로젝트"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "🧑‍💻 네부캠 프로젝트",
              "to": "/docs/intro"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "linkedin",
              "href": "https://www.linkedin.com/in/effozen/"
            },
            {
              "label": "X",
              "href": "https://x.com/effozen"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "🚀 성장이야기",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/effozen"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 Zen's Atelier. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    },
    "metadata": [
      {
        "name": "keywords",
        "content": "프론트엔드 개발, 동기화, Zen, 블로그, 프로그래밍"
      },
      {
        "name": "author",
        "content": "Zen"
      },
      {
        "name": "description",
        "content": "Zen's Atelier - 동기화를 중요하게 생각하는 프론트앤드 개발자"
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "name": "twitter:title",
        "content": "Zen's Atelier"
      },
      {
        "name": "twitter:description",
        "content": "동기화를 중요하게 생각하는 프론트앤드 개발자"
      },
      {
        "name": "twitter:url",
        "content": "https://fantasmith.com"
      },
      {
        "name": "twitter:image",
        "content": "https://fantasmith.com/img/logo.webp"
      },
      {
        "property": "og:title",
        "content": "Zen's Atelier"
      },
      {
        "property": "og:description",
        "content": "동기화를 중요하게 생각하는 프론트앤드 개발자"
      },
      {
        "property": "og:type",
        "content": "website"
      },
      {
        "property": "og:url",
        "content": "https://fantasmith.com"
      },
      {
        "property": "og:image",
        "content": "https://fantasmith.com/img/logo.webp"
      }
    ],
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "plugins": [
    "@docusaurus/theme-live-codeblock"
  ],
  "headTags": [
    {
      "tagName": "link",
      "attributes": {
        "rel": "sitemap",
        "type": "application/xml",
        "title": "Sitemap",
        "href": "https://fantasmith.com/sitemap.xml"
      }
    },
    {
      "tagName": "script",
      "attributes": {
        "type": "application/ld+json"
      },
      "innerHTML": "{\"@context\":\"https://schema.org\",\"@type\":\"Person\",\"name\":\"Zen\",\"url\":\"https://fantasmith.com\",\"sameAs\":[\"https://github.com/effozen\",\"https://www.linkedin.com/in/effozen/\",\"https://x.com/effozen\"],\"jobTitle\":\"프론트엔드 개발자\",\"description\":\"동기화를 중요하게 생각하는 프론트앤드 개발자\"}"
    }
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
